[book]
authors = ["Steve Klabnik", "Carol Nichols", "Příspěvky od komunity Rustu"]
language = "cz"
multilingual = false
src = "src"
title = "Programovací jazyk Rust"

[output.html]
additional-css = ["ferris.css"]
additional-js = ["ferris.js"]
git-repository-url = "https://github.com/pepega007xd/rust-book-cz"
